Feature/epiaswebservices
FurkanCodes/test-template pull request #1
Opened 2024-03-15 15:01 UTC by melisadaglii1

Epiaş Web Servis Güncellendi

2024-03-15 17:46 UTC, FurkanCodes requested changes
Genel olarak arayüzde tableın arkaplanı falan yok, belki bi Card componentine sarmalaman lazım bütün componentleri. Arkaplanı bomboş

2024-03-15 17:46 UTC, FurkanCodes commented on src/modules/dashboards/parametermanagement/ParameterManagement.tsx
> +// @ts-ignore
ts ignore' kaldır, typesafe yap

2024-03-15 17:46 UTC, FurkanCodes commented on src/modules/dashboards/epiaswebservices/components/FilterComponent.tsx
> +const FilterComponent = (onFilter, rows) => {
birbirine benzeyen stateleri useReducer ile ya da obje olarak tek state'de kontrol edebilirsin, araştırabilirsin

2024-03-15 17:46 UTC, FurkanCodes commented on src/modules/dashboards/epiaswebservices/EpiasWebServices.tsx
> +// @ts-ignore
Bu yasak

2024-03-15 17:46 UTC, FurkanCodes commented on src/components/TableComponents/index.tsx
> +// @ts-ignore
Typelardan kaçamazsın

2024-03-18 12:24 UTC, FurkanCodes commented on src/modules/dashboards/epiaswebservices/components/FilterComponent.tsx
> +    const [state, setState] = useState({
Typelarını declare et, bu useStatehangi typeları kullanacak?


Örnek; 
interface IUser {
  name: string;
}
const [user, setUser] = useState<IUser>({name: 'Jon'});

PS. type declarationları features klasoru içerisinde ayrı bi yerde tut

2024-03-18 12:25 UTC, FurkanCodes commented on src/modules/dashboards/epiaswebservices/components/FilterComponent.tsx
> +    return (
Arayüze tam bakamıyorum su an, ama Card componentiyle sarabilirsin demiştim, onun amacı arkaplanda beyaz bi container içerisinde elementleri tutmak, göze daha iyi hitap eder, eğer bunu yaptıysan göz ardı edebilirsin

2024-03-18 12:26 UTC, FurkanCodes commented on src/modules/dashboards/epiaswebservices/EpiasWebServices.tsx
> +    const columnsFirst = [
Buradaki bütün columnları typesafe yapabilirsin

2024-03-18 12:26 UTC, FurkanCodes requested changes
değişiklikler

2024-03-18 12:27 UTC, melisadaglii1 commented
o şekilde yapmıştım card ıle sarmıstım

Veli Furkan TURKOGLU ***@***.***>, 18 Mar 2024 Pzt, 15:25
tarihinde şunu yazdı:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/modules/dashboards/epiaswebservices/components/FilterComponent.tsx
> <https://github.com/FurkanCodes/test-template/pull/1#discussion_r1528444029>
> :
>
> > +            const filteredData = rows.filter(row => {
> +                const rowDate = new Date(row.gasname);
> +                return rowDate >= state.startDate && rowDate <= state.endDate;
> +            });
> +            onFilter(filteredData);
> +        }
> +    };
> +
> +    const toggleState = (key) => {
> +        setState(prevState => ({
> +            ...prevState,
> +            [key]: !prevState[key]
> +        }));
> +    };
> +
> +    return (
>
> Arayüze tam bakamıyorum su an, ama Card componentiyle sarabilirsin
> demiştim, onun amacı arkaplanda beyaz bi container içerisinde elementleri
> tutmak, göze daha iyi hitap eder, eğer bunu yaptıysan göz ardı edebilirsin
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FurkanCodes/test-template/pull/1#pullrequestreview-1942815536>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASVHJLUWXYVD5RSAUH2AJFLYY3MMRAVCNFSM6AAAAABEYFD4TOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNBSHAYTKNJTGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-18 16:22 UTC, merged